config/routes.rb
Trytest::Application.routes.draw do
  
  
  
  ActiveAdmin.routes(self)

  namespace :api, :defaults => {:format => :json} do
    namespace :v1 do
      resources :tkb_giang_viens
      resources :lop_mon_hoc_sinh_viens
      resources :sinh_viens do 
        member do 
          get 'trucnhat' => 'sinh_viens#trucnhat'
          get 'tkb' => 'sinh_viens#tkb'
        end
      end
      resources :giang_viens
      resources :lop_mon_hocs
    end
  end

  match '/rate' => 'rater#create', :as => 'rate'

  get "dashboard/index"
  match '/activity' => "dashboard#activity", :as => "activity"
  match '/calendar' => 'dashboard#calendar', :as => "calendar"
  match '/post_calendar' => 'dashboard#post_calendar', :as => "post_calendar"
  match 'tuan/:id' => 'dashboard#show', :as => "tuan"
  get "dashboard/access_denied", :as => "access_denied"
   root :to => 'dashboard#index'
  devise_for :users do
   get '/users/sign_out' => 'devise/cas_sessions#destroy'
  end
  
  
  
  resources :users
  resources :giang_viens do 
    member do 
      get '/report' => 'giang_viens#report'
    end
  end
  resources :mon_hocs
  resources :sinh_viens
  resources :phongs
  resources :lop_mon_hocs do           
    resources :tkb_giang_viens      
    member do 
      post '/update_hoten' => 'lop_mon_hocs#update_hoten'
      post '/update_diemqt' => 'lop_mon_hocs#update_diemqt'
      post '/update_diemcc' => 'lop_mon_hocs#update_diemcc'
      get '/nhap_diem_thang_3' => 'lop_mon_hocs#nhapdiemthang3', :as => 'nhapdiemthang3'
      post '/postnhapdiemthang3' => 'lop_mon_hocs#postnhapdiemthang3', :as => 'postnhapdiemthang3'
      get '/calendar' => 'lop_mon_hocs#calendar'        
      get '/search' => 'lop_mon_hocs#search'
      get '/report' => 'lop_mon_hocs#report'
      get '/t/:tuan_id' => 'lop_mon_hocs#tuan'
      get '/showdkbs' => 'lop_mon_hocs#showdkbs', :as => 'showdkbs'
      post '/dkbs' => 'lop_mon_hocs#dkbs', :as => 'dkbs'
      post '/qldkbs' => 'lop_mon_hocs#qldkbs', :as => 'qldkbs'
      get '/lichtrinh' => 'lop_mon_hocs#lichtrinh', :as => 'lichtrinh'
      get '/tinhhinh' => 'lop_mon_hocs#tinhhinh', :as => 'tinhhinh'
      get 'phieudiem'
    end    
    resources :diem_chi_tiets      do  
      collection do        
        get '/:loai' => 'diem_chi_tiets#index'
        post '/:loai'  => 'diem_chi_tiets#create'
      end
    end
    resources :diem_chuyen_cans do 
      collection do 
        post '/update' => 'diem_chuyen_cans#update'
      end
    end    
    resources :lop_mon_hoc_sinh_viens  do 
      collection do 
        post '/groupupdate' => 'lop_mon_hoc_sinh_viens#groupupdate'
        get '/group' => 'lop_mon_hoc_sinh_viens#group'
      end
    end  
    resources :topics do 
      resources :posts
    end  
    resources :can_bo_lops
    resources :tai_lieu_mon_hocs
    resources :thong_bao_lop_hocs
    resources :dang_ky_day_bus
    resources :kien_nghis
    resources :nhat_kies
    resources :ra_som_vao_muons
    resources :day_thays
    resources :nghi_days
    resources :buoihoc do 
      member do
        post 'rate' => 'buoihoc#rate'
        post 'update', :as => 'update'          
        post 'diemdanh'
        get 'diemdanh' => 'buoihoc#get_diemdanh'
        post 'calendar'
        post 'daybu'
        post 'nghiday'
        post 'daythay'
        post 'doigio'
        get 'quanly' => 'buoihoc#get_quanly'
        get 'lichtrinh'
        get 'lichtrinh_edit' => 'buoihoc#lichtrinh_edit'
        post 'lichtrinh' => 'buoihoc#syllabus'        
      end        
    end
  end
  get "quanly" => 'quanly#index', :as => 'quanly'
  match 'quanly/lopghep' => 'quanly#lopghep', :as => 'quanlylopghep'
  match 'quanly/nghiday' => 'quanly#nghiday', :as => 'quanlynghiday'
  match 'quanly/daybu' => 'quanly#daybu', :as => 'quanlydaybu'
  match 'quanly/dkbs' => 'quanly#dkbs', :as => 'quanlydkbs'
  post 'quanly/filtersv' => 'quanly#filtersv', :as => 'filtersv'
  post 'quanly/filterlophc' => 'quanly#filterlophc', :as => 'filterlophc'
  post 'quanly/filterloptc' => 'quanly#filterloptc', :as => 'filterloptc'
  post 'quanly/checklopghep' => 'quanly#checklopghep', :as => 'checklopghep'
  post 'quanly/updatelopghep' => 'quanly#updatelopghep', :as => 'updatelopghep'
  post 'quanly/movelopghep' => 'quanly#movelopghep', :as => 'movelopghep'
  post 'quanly/qlnghiday' => 'quanly#qlnghiday', :as => 'qlnghiday'
  post 'quanly/qldaybu' => 'quanly#qldaybu', :as => 'qldaybu'
  post 'quanly/qldkbs' => 'quanly#qldkbs', :as => 'qldkbs'
  get 'quanly/phongtrong' => 'quanly#phongtrong', :as => 'phongtrong'
  post 'quanly/getphongtrong' => 'quanly#getphongtrong', :as => 'getphongtrong'
  match 'quanly/nghidayhangloat' => 'quanly#nghidayhangloat', :as => 'nghidayhangloat'
  post 'quanly/post_nghidayhangloat' => 'quanly#post_nghidayhangloat', :as => 'post_nghidayhangloat'
  post 'quanly/huynghiday' => 'quanly#huynghiday', :as => 'huynghiday'
  get "quanly/report1" => 'quanly#report1', :as => 'report1'
  get "quanly/report2/(:tuan)" => 'quanly#report2', :as => 'report2'
  get "quanly/report3" => 'quanly#report3', :as => 'report3'
  get "quanly/report4/(:tuan)" => 'quanly#report4', :as => 'report4'
  get "quanly/report5/(:tuan)" => 'quanly#report5', :as => 'report5'
  get "monitor" => 'monitor#index', :as => 'monitor'
  get "monitor/activity" => 'monitor#activity', :as => 'activity'
  get "monitor/:lop_mon_hoc_id/:id" => 'monitor#show', :as => 'showmonitor'
  get "monitor/daybu/:lop_mon_hoc_id/:id" => 'monitor#showdaybu', :as => 'showmonitordaybu'
  get "admin" => 'admin#index', :as => 'admin'
  get "trucnhat" => 'monitor#trucnhat', :as => 'trucnhat'
  get "thanhtra" => 'monitor#thanhtra', :as => 'thanhtra'
  get "quanly/vipham" => 'quanly#vipham', :as => 'vipham'
  post "quanly/qlvipham" => 'quanly#qlvipham', :as => 'qlvipham'
  get "quanly/qlvipham(/:tuan)" => 'quanly#qlvipham', :as => 'qlvipham'
  get "monitor/:lop_mon_hoc_id/:phong/:id/trucnhat" => 'monitor#showtrucnhat', :as => 'showtrucnhat'
  get "monitor/:lop_mon_hoc_id/:phong/:id/thanhtra" => 'monitor#showthanhtra', :as => 'showthanhtra'
  post "monitor/qltrucnhat" => 'monitor#qltrucnhat', :as => 'qltrucnhat'
  post "monitor/qlthanhtra" => 'monitor#qlthanhtra', :as => 'qlthanhtra'  
  get "search" => 'dashboard#search', :as => 'search'
  match '*a', :to => 'application#routing'
  
  

  

end

app/controllers/dashboard_controller.rb
#encoding: utf-8
class DashboardController < ApplicationController

  
  before_filter :load_lops, :except => [:search]
  def index    

    @current_lich = @lich.select {|l| l["tuan"] == @current_week}.uniq if @lich
    @current_lich2 = @lich2.select {|l| l["tuan"] == @current_week}.uniq if @lich2
    
    @lichbus = @lichbosungs.select {|l| l.loai == 2 and l.status == 3 and l.tuan == @current_week} if @lichbosungs    
    QC.enqueue "GoogleAnalytic.perform", {:category => "Dashboard", :action => "index", :label => "#{current_user.username}", :value => "1"}.to_json
  end

  def activity
    if current_user.imageable.is_a?(SinhVien)      
      @activities = PublicActivity::Activity.where(recipient_id: current_user.imageable.id).order('updated_at desc').page(params[:page]).per_page(50)
    elsif current_user.imageable and current_user.imageable.is_a?(GiangVien)
      @activities = PublicActivity::Activity.where(owner_id: current_user.id).order('updated_at desc').page(params[:page]).per_page(50)
    elsif current_user.is_admin?
      @activities = PublicActivity::Activity.order('updated_at desc').page(params[:page]).per_page(50)
    end    
    QC.enqueue "GoogleAnalytic.perform", {:category => "Dashboard", :action => "activity", :label => "#{current_user.username}", :value => "1"}.to_json
  end

  def show
    @current_lich = @lich.select {|l| l["tuan"] == params[:id].to_i}.uniq if @lich 
    @current_lich2 = @lich2.select {|l| l["tuan"] == @current_week}.uniq if @lich2
    QC.enqueue "GoogleAnalytic.perform", {:category => "Dashboard", :action => "show", :label => "#{current_user.username}", :value => "1"}.to_json
  end
  def calendar
    @lichbus = []
    @lichdkbs = []
    @lichbus += @lichbosungs.select {|l| l.loai == 2 and l.status == 3} if @lichbosungs
    @lichdkbs += @lichbosungs.select {|l| l.loai == 5 and l.status == 3} if @lichbosungs
    @lichbus += @lichbosungs2.select {|l| l.loai == 2 and l.status == 3} if @lichbosungs2
    @lichdkbs += @lichbosungs2.select {|l| l.loai == 5 and l.status == 3} if @lichbosungs2

    QC.enqueue "GoogleAnalytic.perform", {:category => "Dashboard", :action => "calendar", :label => "#{current_user.username}", :value => "1"}.to_json
    respond_to do |format|
      if @type.is_a?(GiangVien) or current_user.role == 'trogiang'
        format.html { render :calendar }
      else
        format.html { render :calendar_sv }
      end
    end
  end
  def post_calendar
    if @type.is_a?(GiangVien) or current_user.role == 'trogiang'
      lops = params[:lich]
      unless lops.empty?
        lops.each do |k,v|
          lop = LopMonHoc.find(k)
          if lop 
            authorize! :manage, lop
            lop.ngay_thua = {:ngay => v}.to_json
            lop.save!
          end
        end
      end
    end
  end
  def search
    @type = params[:type]
    @keyword = params[:search]
    if params[:type] == '1'
      @search = Sunspot.search(SinhVien) do 
        fulltext params[:search]
        SinhVien::FACETS.each do |f|
          facet(f)
        end        
        with(:lop_hc, params[:lop_hc]) if params[:lop_hc].present?
        with(:ten, params[:ten]) if params[:ten].present?
        with(:ten_nganh, params[:ten_nganh]) if params[:ten_nganh].present?
        with(:ma_khoa_hoc, params[:ma_khoa_hoc]) if params[:ma_khoa_hoc].present?
        paginate(:page => params[:page] || 1, :per_page => 50)
      end
      @results = @search.results
    elsif params[:type] == '2'
      @search = Sunspot.search(LopMonHoc) do 
        fulltext params[:search]
        
        LopMonHoc::FACETS.each do |f|
          facet(f)
        end        
        with(:ten_mon_hoc, params[:ten_mon_hoc]) if params[:ten_mon_hoc].present?
        with(:ten_giang_vien, params[:ten_giang_vien]) if params[:ten_giang_vien].present?
        with(:phong_hoc, params[:phong_hoc]) if params[:phong_hoc].present?
        paginate(:page => params[:page] || 1, :per_page => 50)
      end
      @results = @search.results
    end    
    QC.enqueue "GoogleAnalytic.perform", {:category => "Dashboard", :action => "search", :label => "#{current_user.username}", :value => "1"}.to_json
    respond_to do |format|      
      format.html      
    end
  end
  protected
  def to_zdate(str)
    DateTime.strptime(str.gsub("T","-").gsub("Z",""), "%Y-%m-%d-%H:%M").change(:offset => Rational(7,24))
  end
  def load_lops    
    
    
    @type = current_user.imageable
    if @type        	
    	@current_lops = @type.lop_mon_hocs
      @lop_xongs = @current_lops.select {|t| t and t.da_day_xong == true}.map {|k| k and k.id}
      @lich = @type.get_days[:ngay].uniq if @type.get_days
      @lichthua = []
      if @current_lops.count > 0
        @current_lops.each do |lop|
          if lop.ngay_thua
            thua = JSON.parse(lop.ngay_thua)
            @lichthua += thua["ngay"] if thua and thua["ngay"]
          end
        end
      end
      @lichbosungs = @type.lich_trinh_giang_days.select {|l| [1,2,3,4,5].include?(l.loai)}

      generator = ColorGenerator.new saturation: 0.3, lightness: 0.75
      @color = [] 
      20.times do |i|
        @color << generator.create_hex
      end
      @color_map = {}
      @info = {}
      unless @current_lops.empty?
        @current_lops.each_with_index do |l,i|
          @color_map["#{l.ma_lop}-#{l.ma_mon_hoc}"] = @color[i] if l 
        end           
      end
      unless @lichbosungs.empty?
        @lichbosungs.each_with_index do |l,i|
          @color_map["#{l.ngay_day.localtime.strftime('%Y-%m-%d-%H:%M')}"] = "A00000"
          @info["#{l.ngay_day.localtime.strftime('%Y-%m-%d-%H:%M')}"] = l.info
        end
      end
    else
      @current_lops = []
    end


    
    @current_lops2 = current_user.lop_mon_hocs
    @lop_xongs2 = @current_lops2.select {|t| t and t.da_day_xong == true}.map {|k| k and k.id}
    @lichbosungs2 = current_user.lich_trinh_giang_days.select {|l| [1,2,3,4,5].include?(l.loai)}
    @lich2 = current_user.get_days[:ngay].uniq if current_user.get_days
    #@lichthua2 = current_user.get_thua[:ngay].uniq if current_user.get_thua
    @lichthua2 = []
    if @current_lops2.count > 0
      @current_lops2.each do |lop|
        if lop.ngay_thua
          thua = JSON.parse(lop.ngay_thua)
          @lichthua2 += thua["ngay"] if thua and thua["ngay"]
        end
      end
    end

    generator = ColorGenerator.new saturation: 0.2, lightness: 0.8
    @color2 = [] 
    20.times do |i|
      @color2 << generator.create_hex
    end
    @color_map2 = {}
    @info2 = {}
    unless @current_lops2.empty?
      @current_lops2.each_with_index do |l,i|
        @color_map2["#{l.ma_lop}-#{l.ma_mon_hoc}"] = @color2[i] if l 
      end           
    end
    unless @lichbosungs2.empty?
      @lichbosungs2.each_with_index do |l,i|
        @color_map2["#{l.ngay_day.localtime.strftime('%Y-%m-%d-%H:%M')}"] = "A00000"
        @info2["#{l.ngay_day.localtime.strftime('%Y-%m-%d-%H:%M')}"] = l.info
      end
    end
  end

end

app/helpers/dashboard_helper.rb
module DashboardHelper
	 def darken_color(hex_color, amount=0.4)
		hex_color = hex_color.gsub('#','')
		rgb = hex_color.scan(/../).map {|color| color.hex}
		rgb[0] = (rgb[0].to_i * amount).round
		rgb[1] = (rgb[1].to_i * amount).round
		rgb[2] = (rgb[2].to_i * amount).round
		"#%02x%02x%02x" % rgb
		end
		# Amount should be a decimal between 0 and 1. Higher means lighter
		def lighten_color(hex_color, amount=0.6)
		hex_color = hex_color.gsub('#','')
		rgb = hex_color.scan(/../).map {|color| color.hex}
		rgb[0] = [(rgb[0].to_i + 255 * amount).round, 255].min
		rgb[1] = [(rgb[1].to_i + 255 * amount).round, 255].min
		rgb[2] = [(rgb[2].to_i + 255 * amount).round, 255].min
		"#%02x%02x%02x" % rgb
		end
	def contrasting_text_color(hex_color)
	  color = hex_color.gsub('#','')
	  convert_to_brightness_value(color) > 382.5 ? darken_color(color) : lighten_color(color)
	end
	def convert_to_brightness_value(hex_color)
	  (hex_color.scan(/../).map {|color| color.hex}).sum
	end
	def check_thua?(co, t)
		return false if co.nil?
		co.include?(t)
	end
	def check_day_xong?(co, l)
		return false if co.nil?
		co.include?(l)
	end
end

app/views/dashboard/_activity.html.haml
= render_activities(activities)
  

app/views/dashboard/_result_giangvien.html.haml
%colgroup
  %col{:style => "width: 3%"}
  %col{:style => "width: 17%"}
  %col{:style => "width: 7%"}
  %col{:style => "width: 25%"}                    
  %col{:style => "width: 8%"}                    
  %col{:style => "width: 15%"}    
  %col{:style => "width: 15%"} 
  %col{:style => "width: 10%"}         
%thead
  %td STT
  %td Giảng viên
  %td Mã lớp
  %td Môn học
  %td Phòng
  %td Khối lượng thực hiện
  %td Khối lượng phân bổ
  %td Xuất
%tbody
  - if @results and @results.count > 0
    - @results.each_with_index do |lop, index|
      - if lop.giang_vien
        %tr
          %td= (index+1).to_s
          %td= link_to lop.ten_giang_vien, giang_vien_path(lop.ma_giang_vien)
          %td= link_to lop.ma_lop, report_lop_mon_hoc_path(lop.id)
          %td= lop.ten_mon_hoc 
          %td= (link_to lop.phong_hoc, phong_path(lop.phong_hoc) if lop.phong_hoc) || ""
          %td= lop.khoi_luong.to_s
          %td= (lop.so_tiet_phan_bo || lop.khoi_luong_phan_bo)
          %td= link_to "Xuất ra Excel", search_lop_mon_hoc_path(lop.id) + ".xlsx"

app/views/dashboard/access_denied.html.haml
%h1 You are not authorized

app/views/dashboard/activity.js.haml
$('.activities').append('#{escape_javascript(render partial: "activity", :locals => { :activities => @activities })}');
$('a.load-more-posts').attr('href', '#{activity_path page: @activities.next_page}');
 
- unless @activities.next_page
  $('a.load-more-posts').remove();

app/views/dashboard/calendar.html.haml
.container-fluid
  .navbar.navbar-fixed-top
    .navbar-inner
      .container-fluid
        %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.brand{:href => "/" } HPU
        .container.nav-collapse
          %ul.nav.pull-left#urls           
            - if can? :quanly, @lop_mon_hoc 
              %li.active= link_to "Thời khóa biểu", "/calendar"
            %li= link_to "Thăm dò", "http://thamdo.hpu.edu.vn"
          %ul.nav.pull-right            
            %li= link_to 'Đăng xuất', destroy_user_session_path  
.container-fluid{:style=>"margin-top: 4%;"}
  .row-fluid
    %ul.nav.pull-right
      %li
        %i
          %strong
            %span= current_user.fullname

      %li
        %i
          %span= "Tuần #{@current_week}: Từ ngày #{@week.tu_ngay.localtime.mday}/#{@week.tu_ngay.localtime.mon}, đến ngày #{@week.den_ngay.localtime.mday}/#{@week.den_ngay.localtime.mon}"
  .row-fluid
    .well.sidebar-nav{:style => "font-size: 12px; font-weight: bold;"}
      Đối với các lớp được phân bổ thừa giờ, bạn có thể bỏ các tiết thừa bằng cách chọn và nhấn cập nhật ở thời khóa biểu
  = form_tag post_calendar_path, :method => :post, :remote => true do
    = submit_tag "Cập nhật", :class =>"btn btn-primary",  :data => {disable_with: "Submitting..."}
    - if @lich
      %h5 Lớp chính
      %table#monitor{:class => "table table-bordered"}      
        %thead    
          %td Tuần    
          %td Thời gian 
          %td Số tiết      
          %td Phòng    
          %td Môn
          %td Mã lớp
          %td Giờ thừa?
        %tbody        
          - @lich.each_with_index do |lich, index|
            %tr                                    
              %td{:style => "background: ##{@color_map["#{lich["ma_lop"]}-#{lich["ma_mon_hoc"]}"]}" }= link_to "T"  + (("0" if lich["tuan"] < 10) || "") +lich["tuan"].to_s, tuan_path(lich["tuan"].to_s)
              %td{:style => "background: ##{@color_map["#{lich["ma_lop"]}-#{lich["ma_mon_hoc"]}"]}" }= link_to TkbGiangVien::THU2[lich["thu"]] + ", ngày " + DateTime.parse(lich["time"][0]).strftime("%d/%m") + ", " + DateTime.parse(lich["time"][0]).strftime("%Hh:%M") , lop_mon_hoc_buoihoc_path(lich["lop"], DateTime.parse(lich["time"][0]).strftime("%Y-%m-%d-%H-%M")), :style => "color: ##{@color_map[DateTime.parse(lich["time"][0]).strftime("%Y-%m-%d-%H:%M")]}", :rel => "tooltip", :'data-original-title' => "#{@info2[DateTime.parse(lich["time"][0]).strftime("%Y-%m-%d-%H:%M")]}"
              %td{:style => "background: ##{@color_map["#{lich["ma_lop"]}-#{lich["ma_mon_hoc"]}"]}" }= lich["so_tiet"]             
              %td{:style => "background: ##{@color_map["#{lich["ma_lop"]}-#{lich["ma_mon_hoc"]}"]}" }= lich["phong"]                 
              %td{:style => "background: ##{@color_map["#{lich["ma_lop"]}-#{lich["ma_mon_hoc"]}"]}" }= lich["ten_mon_hoc"]
              %td{:style => "background: ##{@color_map["#{lich["ma_lop"]}-#{lich["ma_mon_hoc"]}"]}" }= link_to lich["ma_lop"], lop_mon_hoc_path(lich["lop"])
              %td{:style => "background: ##{@color_map["#{lich["ma_lop"]}-#{lich["ma_mon_hoc"]}"]}" }= check_box_tag "lich[#{lich["lop"]}][]", lich["time"][0], check_thua?(@lichthua, lich["time"][0]), :disabled => check_day_xong?(@lop_xongs, lich["lop"])
    %br
    - if @lich2
      %h5 Lớp trợ giảng
      %table#monitor{:class => "table table-bordered"}      
        %thead    
          %td Tuần    
          %td Thời gian 
          %td Số tiết      
          %td Phòng    
          %td Môn
          %td Mã lớp
          %td Giờ thừa?
        %tbody            
          - @lich2.each_with_index do |lich, index|
            %tr        
              %td{:style => "background: ##{@color_map2["#{lich["ma_lop"]}-#{lich["ma_mon_hoc"]}"]}" }= link_to "T" + (("0" if lich["tuan"] < 10) || "") + lich["tuan"].to_s, tuan_path(lich["tuan"].to_s)
              %td{:style => "background: ##{@color_map2["#{lich["ma_lop"]}-#{lich["ma_mon_hoc"]}"]}" }= link_to TkbGiangVien::THU2[lich["thu"]] + ", ngày " + DateTime.parse(lich["time"][0]).strftime("%d/%m") + ", " + DateTime.parse(lich["time"][0]).strftime("%Hh:%M") , lop_mon_hoc_buoihoc_path(lich["lop"], DateTime.parse(lich["time"][0]).strftime("%Y-%m-%d-%H-%M")), :style => "color: ##{@color_map2[DateTime.parse(lich["time"][0]).strftime("%Y-%m-%d-%H:%M")]}", :rel => "tooltip", :'data-original-title' => "#{@info2[DateTime.parse(lich["time"][0]).strftime("%Y-%m-%d-%H:%M")]}"
              %td{:style => "background: ##{@color_map2["#{lich["ma_lop"]}-#{lich["ma_mon_hoc"]}"]}" }= lich["so_tiet"]             
              %td{:style => "background: ##{@color_map2["#{lich["ma_lop"]}-#{lich["ma_mon_hoc"]}"]}" }= lich["phong"]                 
              %td{:style => "background: ##{@color_map2["#{lich["ma_lop"]}-#{lich["ma_mon_hoc"]}"]}" }= lich["ten_mon_hoc"]
              %td{:style => "background: ##{@color_map2["#{lich["ma_lop"]}-#{lich["ma_mon_hoc"]}"]}" }= link_to lich["ma_lop"], lop_mon_hoc_path(lich["lop"])
              %td{:style => "background: ##{@color_map2["#{lich["ma_lop"]}-#{lich["ma_mon_hoc"]}"]}" }= check_box_tag "lich[#{lich["lop"]}][]", lich["time"][0], check_thua?(@lichthua2, lich["time"][0]), :disabled => check_day_xong?(@lop_xongs2, lich["lop"])
  - if @lichdkbs and @lichdkbs.count > 0
    %h5 Lịch dạy bổ sung
    %table{:class => "table table-bordered"}
      %thead    
        %td Tuần                  
        %td Số tiết      
        %td Thời gian  
        %td Phòng    
        %td Môn
        %td Mã lớp
        %td Trạng thái
      %tbody
        - @lichdkbs.each_with_index do |lich, index|                  
          %tr            
            %td= link_to "T"  + (("0" if lich.tuan < 10) || "") +lich.tuan.to_s, tuan_path(lich.tuan.to_s)
            %td= link_to TkbGiangVien::THU2[lich.wday] + ", ngày " +lich.ngay_day.localtime.strftime("%d/%m") + ", " + lich.ngay_day.localtime.strftime("%Hh:%M") , lop_mon_hoc_buoihoc_path(lich.lop_mon_hoc_id, lich.ngay_day.localtime.strftime("%Y-%m-%d-%H-%M"))
            %td= lich.so_tiet_day
            %td= lich.phong
            %td= lich.lop_mon_hoc.ten_mon_hoc
            %td= link_to lich.lop_mon_hoc.ma_lop, lop_mon_hoc_path(lich.lop_mon_hoc.id)
            %td= lich.trangthai

  - if @lichbus and @lichbus.count > 0
    %h5 Lịch dạy bù
    %table{:class => "table table-bordered"}
      %thead    
        %td Tuần    
        %td Thời gian 
        %td Ngày gốc
        %td Số tiết      
        %td Phòng    
        %td Môn
        %td Mã lớp
        %td Trạng thái
      %tbody
        - @lichbus.each_with_index do |lich, index|
          %tr
            %td= link_to "T"  + (("0" if lich.tuan < 10) || "") +lich.tuan.to_s, tuan_path(lich.tuan.to_s)
            %td= link_to TkbGiangVien::THU2[lich.wday] + ", ngày " +lich.ngay_day_moi.localtime.strftime("%d/%m") + ", " + lich.ngay_day_moi.localtime.strftime("%Hh:%M") , lop_mon_hoc_buoihoc_path(lich.lop_mon_hoc_id, lich.ngay_day.localtime.strftime("%Y-%m-%d-%H-%M"))
            %td= TkbGiangVien::THU2[lich.wday] + ", ngày " +lich.ngay_day.localtime.strftime("%d/%m") + ", " + lich.ngay_day.localtime.strftime("%Hh:%M")
            %td= lich.so_tiet_day
            %td= lich.phong_moi
            %td= lich.lop_mon_hoc.ten_mon_hoc
            %td= link_to lich.lop_mon_hoc.ma_lop, lop_mon_hoc_path(lich.lop_mon_hoc.id)
            %td= lich.trangthai

app/views/dashboard/post_calendar.js.haml
alert("OK");