config/routes.rb
Trytest::Application.routes.draw do
  
  
  
  ActiveAdmin.routes(self)

  namespace :api, :defaults => {:format => :json} do
    namespace :v1 do
      resources :tkb_giang_viens
      resources :lop_mon_hoc_sinh_viens
      resources :sinh_viens do 
        member do 
          get 'trucnhat' => 'sinh_viens#trucnhat'
          get 'tkb' => 'sinh_viens#tkb'
        end
      end
      resources :giang_viens
      resources :lop_mon_hocs
    end
  end

  match '/rate' => 'rater#create', :as => 'rate'

  get "dashboard/index"
  match '/activity' => "dashboard#activity", :as => "activity"
  match '/calendar' => 'dashboard#calendar', :as => "calendar"
  match '/post_calendar' => 'dashboard#post_calendar', :as => "post_calendar"
  match 'tuan/:id' => 'dashboard#show', :as => "tuan"
  get "dashboard/access_denied", :as => "access_denied"
   root :to => 'dashboard#index'
  devise_for :users do
   get '/users/sign_out' => 'devise/cas_sessions#destroy'
  end
  
  
  
  resources :users
  resources :giang_viens do 
    member do 
      get '/report' => 'giang_viens#report'
    end
  end
  resources :mon_hocs
  resources :sinh_viens
  resources :phongs
  resources :lop_mon_hocs do           
    resources :tkb_giang_viens      
    member do 
      post '/update_hoten' => 'lop_mon_hocs#update_hoten'
      post '/update_diemqt' => 'lop_mon_hocs#update_diemqt'
      post '/update_diemcc' => 'lop_mon_hocs#update_diemcc'
      get '/nhap_diem_thang_3' => 'lop_mon_hocs#nhapdiemthang3', :as => 'nhapdiemthang3'
      post '/postnhapdiemthang3' => 'lop_mon_hocs#postnhapdiemthang3', :as => 'postnhapdiemthang3'
      get '/calendar' => 'lop_mon_hocs#calendar'        
      get '/search' => 'lop_mon_hocs#search'
      get '/report' => 'lop_mon_hocs#report'
      get '/t/:tuan_id' => 'lop_mon_hocs#tuan'
      get '/showdkbs' => 'lop_mon_hocs#showdkbs', :as => 'showdkbs'
      post '/dkbs' => 'lop_mon_hocs#dkbs', :as => 'dkbs'
      post '/qldkbs' => 'lop_mon_hocs#qldkbs', :as => 'qldkbs'
      get '/lichtrinh' => 'lop_mon_hocs#lichtrinh', :as => 'lichtrinh'
      get '/tinhhinh' => 'lop_mon_hocs#tinhhinh', :as => 'tinhhinh'
      get 'phieudiem'
    end    
    resources :diem_chi_tiets      do  
      collection do        
        get '/:loai' => 'diem_chi_tiets#index'
        post '/:loai'  => 'diem_chi_tiets#create'
      end
    end
    resources :diem_chuyen_cans do 
      collection do 
        post '/update' => 'diem_chuyen_cans#update'
      end
    end    
    resources :lop_mon_hoc_sinh_viens  do 
      collection do 
        post '/groupupdate' => 'lop_mon_hoc_sinh_viens#groupupdate'
        get '/group' => 'lop_mon_hoc_sinh_viens#group'
      end
    end  
    resources :topics do 
      resources :posts
    end  
    resources :can_bo_lops
    resources :tai_lieu_mon_hocs
    resources :thong_bao_lop_hocs
    resources :dang_ky_day_bus
    resources :kien_nghis
    resources :nhat_kies
    resources :ra_som_vao_muons
    resources :day_thays
    resources :nghi_days
    resources :buoihoc do 
      member do
        post 'rate' => 'buoihoc#rate'
        post 'update', :as => 'update'          
        post 'diemdanh'
        get 'diemdanh' => 'buoihoc#get_diemdanh'
        post 'calendar'
        post 'daybu'
        post 'nghiday'
        post 'daythay'
        post 'doigio'
        get 'quanly' => 'buoihoc#get_quanly'
        get 'lichtrinh'
        get 'lichtrinh_edit' => 'buoihoc#lichtrinh_edit'
        post 'lichtrinh' => 'buoihoc#syllabus'        
      end        
    end
  end
  get "quanly" => 'quanly#index', :as => 'quanly'
  match 'quanly/lopghep' => 'quanly#lopghep', :as => 'quanlylopghep'
  match 'quanly/nghiday' => 'quanly#nghiday', :as => 'quanlynghiday'
  match 'quanly/daybu' => 'quanly#daybu', :as => 'quanlydaybu'
  match 'quanly/dkbs' => 'quanly#dkbs', :as => 'quanlydkbs'
  post 'quanly/filtersv' => 'quanly#filtersv', :as => 'filtersv'
  post 'quanly/filterlophc' => 'quanly#filterlophc', :as => 'filterlophc'
  post 'quanly/filterloptc' => 'quanly#filterloptc', :as => 'filterloptc'
  post 'quanly/checklopghep' => 'quanly#checklopghep', :as => 'checklopghep'
  post 'quanly/updatelopghep' => 'quanly#updatelopghep', :as => 'updatelopghep'
  post 'quanly/movelopghep' => 'quanly#movelopghep', :as => 'movelopghep'
  post 'quanly/qlnghiday' => 'quanly#qlnghiday', :as => 'qlnghiday'
  post 'quanly/qldaybu' => 'quanly#qldaybu', :as => 'qldaybu'
  post 'quanly/qldkbs' => 'quanly#qldkbs', :as => 'qldkbs'
  get 'quanly/phongtrong' => 'quanly#phongtrong', :as => 'phongtrong'
  post 'quanly/getphongtrong' => 'quanly#getphongtrong', :as => 'getphongtrong'
  match 'quanly/nghidayhangloat' => 'quanly#nghidayhangloat', :as => 'nghidayhangloat'
  post 'quanly/post_nghidayhangloat' => 'quanly#post_nghidayhangloat', :as => 'post_nghidayhangloat'
  post 'quanly/huynghiday' => 'quanly#huynghiday', :as => 'huynghiday'
  get "quanly/report1" => 'quanly#report1', :as => 'report1'
  get "quanly/report2/(:tuan)" => 'quanly#report2', :as => 'report2'
  get "quanly/report3" => 'quanly#report3', :as => 'report3'
  get "quanly/report4/(:tuan)" => 'quanly#report4', :as => 'report4'
  get "quanly/report5/(:tuan)" => 'quanly#report5', :as => 'report5'
  get "monitor" => 'monitor#index', :as => 'monitor'
  get "monitor/activity" => 'monitor#activity', :as => 'activity'
  get "monitor/:lop_mon_hoc_id/:id" => 'monitor#show', :as => 'showmonitor'
  get "monitor/daybu/:lop_mon_hoc_id/:id" => 'monitor#showdaybu', :as => 'showmonitordaybu'
  get "admin" => 'admin#index', :as => 'admin'
  get "trucnhat" => 'monitor#trucnhat', :as => 'trucnhat'
  get "thanhtra" => 'monitor#thanhtra', :as => 'thanhtra'
  get "quanly/vipham" => 'quanly#vipham', :as => 'vipham'
  post "quanly/qlvipham" => 'quanly#qlvipham', :as => 'qlvipham'
  get "quanly/qlvipham(/:tuan)" => 'quanly#qlvipham', :as => 'qlvipham'
  get "monitor/:lop_mon_hoc_id/:phong/:id/trucnhat" => 'monitor#showtrucnhat', :as => 'showtrucnhat'
  get "monitor/:lop_mon_hoc_id/:phong/:id/thanhtra" => 'monitor#showthanhtra', :as => 'showthanhtra'
  post "monitor/qltrucnhat" => 'monitor#qltrucnhat', :as => 'qltrucnhat'
  post "monitor/qlthanhtra" => 'monitor#qlthanhtra', :as => 'qlthanhtra'  
  get "search" => 'dashboard#search', :as => 'search'
  match '*a', :to => 'application#routing'
  
  

  

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  attr_accessible :locked, :lop_mon_hoc_id, :posts_count, :title, :body, :user_id

  attr_accessor :body

  has_many :posts, :dependent => :destroy
  belongs_to :lop_mon_hoc, :counter_cache => true
  belongs_to :user

  validates :title, :presence => true
  validates :body, :presence => true, :on => :create
  validates :posts, :presence => true, :allow_nil => false, :on => :update
  validates :user, :presence => true

  default_scope :order => 'updated_at DESC'
  after_create :create_initial_post

  private
    def create_initial_post
      return self.posts.build(:body => self.body) do |post|
        post.lop_mon_hoc = self.lop_mon_hoc
        post.user = self.user
        if self.user.imageable
	        self.user.imageable.topics_count ||= 0 
	        self.user.imageable.topics_count += 1 	        
	      end
        post.save
      end
    end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_filter :load_lop
  # GET /topics
  # GET /topics.json
  def index
    @topics = @lop_mon_hoc.topics

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @topics }
    end
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
    @topic = @lop_mon_hoc.topics.find(params[:id])
    @posts = @topic.posts
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @topic }
    end
  end

  # GET /topics/new
  # GET /topics/new.json
  def new
    @topic = @lop_mon_hoc.topics.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @topic }
    end
  end

  # GET /topics/1/edit
  def edit
    @topic = @lop_mon_hoc.topics.find(params[:id])
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = @lop_mon_hoc.topics.build(params[:topic])
    @topic.user ||= current_user
    
    respond_to do |format|
      if @topic.save
        format.html { redirect_to lop_mon_hoc_topics_path(@lop_mon_hoc), notice: 'Thong bao lop hoc was successfully created.' }
        format.json { render json: @topic, status: :created, location: @topic }
        format.js
      else
        format.html { render action: "new" }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /topics/1
  # PUT /topics/1.json
  def update
    @topic = @lop_mon_hoc.topics.find(params[:id])

    respond_to do |format|
      if @topic.update_attributes(params[:topic])
        format.html { redirect_to [@lop_mon_hoc,@topic], notice: 'Thong bao lop hoc was successfully updated.' }
        format.json { head :no_content }
        format.js
      else
        format.html { render action: "edit" }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic = @lop_mon_hoc.topics.find(params[:id])
    @topic.destroy

    respond_to do |format|
      format.html { redirect_to lop_mon_hoc_topics_url(@lop_mon_hoc) }
      format.json { head :no_content }
      format.js
    end
  end

  protected
  def load_lop
    @lop_mon_hoc = LopMonHoc.find(params[:lop_mon_hoc_id])
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.haml
= form_for [@lop_mon_hoc,@topic], :html => { :multipart => true } do |f|
  - if @topic.errors.any?
    #error_explanation
      %h2= "#{pluralize(@topic.errors.count, "error")} prohibited this thong_bao_lop_hoc from being saved:"
      %ul
        - @topic.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label "Tiêu đề"
    = f.text_field :title
  .field
    = f.label "Nội dung"
    = f.text_area :body, :class => 'ckeditor' 
  
  

  .actions
    = f.submit 'Save', :class => "btn primary"

app/views/topics/destroy.js.haml
$("tr##{@topic.id}").remove();

alert("Xóa chủ đề thành công");

app/views/topics/index.html.haml
.container-fluid
  .navbar.navbar-fixed-top
    .navbar-inner
      .container-fluid
        %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.brand{:href => "/" } HPU
        .container.nav-collapse
          %ul.nav.pull-left#urls            
            %li= link_to "Thông tin chung", lop_mon_hoc_path(@lop_mon_hoc.id)        
            %li.dropdown.active
              %a.dropdown-toggle{:href => "#", :'data-toggle' => "dropdown"} 
                Điểm
                %b.caret
              %ul.dropdown-menu
                - if @lop_mon_hoc.get_thuc_hanh
                  %li= link_to "Điểm nhóm thực hành", lop_mon_hoc_diem_chi_tiets_path(@lop_mon_hoc.id) + "/2"
                %li= link_to "Điểm chuyên cần", lop_mon_hoc_diem_chuyen_cans_path(@lop_mon_hoc.id)        
                %li= link_to "Điểm kiểm tra", lop_mon_hoc_diem_chi_tiets_path(@lop_mon_hoc.id)
            %li.dropdown
              = render 'lop_mon_hoc_sinh_viens/menu'

          %ul.nav.pull-right
            %li= link_to 'Chủ đề mới', new_lop_mon_hoc_topic_path(@lop_mon_hoc)
            %li= link_to 'Đăng xuất', destroy_user_session_path
.container-fluid{:style=>"margin-top: 4%;"}    
  
  %table{:class => "table table-condensed datatable"}
    %colgroup
      %col{:style => "width: 20%"}
      %col{:style => "width: 20%"}
      %col{:style => "width: 60%"}        
    %thead      
      %td Ngày tạo
      %td Người tạo
      %td Tiêu đề        
      
    %tbody
      - @topics.each do |topic|
        %tr{:id => "#{topic.id}"}                                  
          %td= link_to topic.created_at, [@lop_mon_hoc,topic], :'data-pjax' => '#pjax_container'  
          %td= current_user.username
          %td
            = link_to topic.title, [@lop_mon_hoc, topic], :'data-pjax' => '#pjax_container'  
            %hr
            = link_to "Xóa", [@lop_mon_hoc, @topic], :method => :delete, :remote => true, :class => "btn", :data => { :confirm => 'Bạn có chắc muốn xóa chủ đề này?' }
                 

app/views/topics/new.html.haml
.container-fluid
  .navbar.navbar-fixed-top
    .navbar-inner
      .container-fluid
        %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.brand{:href => "/" } HPU
        .container.nav-collapse
          %ul.nav.pull-left#urls            
            %li= link_to "Thông tin chung", lop_mon_hoc_path(@lop_mon_hoc.id)           
            %li.dropdown
              = render 'lop_mon_hoc_sinh_viens/menu'
            %li.dropdown.active
              %a.dropdown-toggle{:href => "#", :'data-toggle' => "dropdown"} 
                Quản lý
                %b.caret
              %ul.dropdown-menu
                %li= link_to "Thông báo", lop_mon_hoc_thong_bao_lop_hocs_path(@lop_mon_hoc.id)   
                %li.active= link_to "Diễn đàn", lop_mon_hoc_topics_path(@lop_mon_hoc.id)         
                %li= link_to "Quản lý lớp học", lop_mon_hoc_lop_mon_hoc_sinh_viens_path(@lop_mon_hoc.id)
                %li= link_to "Thời khóa biểu", lop_mon_hoc_path(@lop_mon_hoc.id)+'/calendar'

          %ul.nav.pull-right
            %li= link_to 'Quay lại', lop_mon_hoc_thong_bao_lop_hocs_path(@lop_mon_hoc)


.container-fluid{:style=>"margin-top: 4%;"}   

  = render 'form'

app/views/topics/show.html.haml
.container-fluid
  .navbar.navbar-fixed-top
    .navbar-inner
      .container-fluid
        %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.brand{:href => "/"} HPU
        .container.nav-collapse
          %ul.nav.pull-left#urls            
            %li= link_to "Thông tin chung", lop_mon_hoc_path(@lop_mon_hoc.id)
            %li.dropdown
              = render 'lop_mon_hoc_sinh_viens/menu'
            %li.dropdown.active
              %a.dropdown-toggle{:href => "#", :'data-toggle' => "dropdown"} 
                Quản lý
                %b.caret
              %ul.dropdown-menu
                %li= link_to "Thông báo", lop_mon_hoc_thong_bao_lop_hocs_path(@lop_mon_hoc.id)
                %li.active= link_to "Diễn đàn", lop_mon_hoc_topics_path(@lop_mon_hoc.id)
                %li= link_to "Quản lý lớp học", lop_mon_hoc_lop_mon_hoc_sinh_viens_path(@lop_mon_hoc.id)
                %li= link_to "Thời khóa biểu", lop_mon_hoc_path(@lop_mon_hoc.id)+'/calendar'

          %ul.nav.pull-right
            %li= link_to 'Chủ đề mới', new_lop_mon_hoc_topic_path(@lop_mon_hoc)
            %li= link_to 'Đăng xuất', destroy_user_session_path

.container-fluid{:style=>"margin-top: 4%;"}    
  %ul.nav.pull-left
    %li= link_to 'Quay lại diễn đàn', lop_mon_hoc_topics_path(@lop_mon_hoc), :class => 'btn'
  %table#myTable{:class => "table table-condensed datatable"}
    %colgroup
      %col{:style => "width: 10%"}
      %col{:style => "width: 90%"}     
    %thead      
      %td Tác giả
      %td= @topic.title             
    %tbody
      - @posts.each do |post|
        %tr{:id => "#{post.id}"}
          %td= post.user.username  
          %td
            = raw(post.body)        
            %hr
            = link_to "Xóa", [@lop_mon_hoc, @topic, post], :method => :delete, :remote => true, :class => "btn", :data => { :confirm => 'Bạn có chắc muốn xóa phản hồi này?' }


  = form_tag lop_mon_hoc_topic_posts_path(@lop_mon_hoc, @topic) , :method => :post, :remote => true do 
    = text_area_tag "post[body]", nil, :value => "", :class => 'redactor', :style => "width: 100%; height: 30%;", :rows => 10
    = submit_tag "Phản hồi nhanh", :class =>"btn btn-success"  
  
  %ul.nav.pull-left
    %li= link_to 'Quay lại diễn đàn', lop_mon_hoc_topics_path(@lop_mon_hoc), :class => 'btn'