config/routes.rb
Trytest::Application.routes.draw do
  
  
  
  ActiveAdmin.routes(self)

  namespace :api, :defaults => {:format => :json} do
    namespace :v1 do
      resources :tkb_giang_viens
      resources :lop_mon_hoc_sinh_viens
      resources :sinh_viens do 
        member do 
          get 'trucnhat' => 'sinh_viens#trucnhat'
          get 'tkb' => 'sinh_viens#tkb'
        end
      end
      resources :giang_viens
      resources :lop_mon_hocs
    end
  end

  match '/rate' => 'rater#create', :as => 'rate'

  get "dashboard/index"
  match '/activity' => "dashboard#activity", :as => "activity"
  match '/calendar' => 'dashboard#calendar', :as => "calendar"
  match '/post_calendar' => 'dashboard#post_calendar', :as => "post_calendar"
  match 'tuan/:id' => 'dashboard#show', :as => "tuan"
  get "dashboard/access_denied", :as => "access_denied"
   root :to => 'dashboard#index'
  devise_for :users do
   get '/users/sign_out' => 'devise/cas_sessions#destroy'
  end
  
  
  
  resources :users
  resources :giang_viens do 
    member do 
      get '/report' => 'giang_viens#report'
    end
  end
  resources :mon_hocs
  resources :sinh_viens
  resources :phongs
  resources :lop_mon_hocs do           
    resources :tkb_giang_viens      
    member do 
      post '/update_hoten' => 'lop_mon_hocs#update_hoten'
      post '/update_diemqt' => 'lop_mon_hocs#update_diemqt'
      post '/update_diemcc' => 'lop_mon_hocs#update_diemcc'
      get '/nhap_diem_thang_3' => 'lop_mon_hocs#nhapdiemthang3', :as => 'nhapdiemthang3'
      post '/postnhapdiemthang3' => 'lop_mon_hocs#postnhapdiemthang3', :as => 'postnhapdiemthang3'
      get '/calendar' => 'lop_mon_hocs#calendar'        
      get '/search' => 'lop_mon_hocs#search'
      get '/report' => 'lop_mon_hocs#report'
      get '/t/:tuan_id' => 'lop_mon_hocs#tuan'
      get '/showdkbs' => 'lop_mon_hocs#showdkbs', :as => 'showdkbs'
      post '/dkbs' => 'lop_mon_hocs#dkbs', :as => 'dkbs'
      post '/qldkbs' => 'lop_mon_hocs#qldkbs', :as => 'qldkbs'
      get '/lichtrinh' => 'lop_mon_hocs#lichtrinh', :as => 'lichtrinh'
      get '/tinhhinh' => 'lop_mon_hocs#tinhhinh', :as => 'tinhhinh'
      get 'phieudiem'
    end    
    resources :diem_chi_tiets      do  
      collection do        
        get '/:loai' => 'diem_chi_tiets#index'
        post '/:loai'  => 'diem_chi_tiets#create'
      end
    end
    resources :diem_chuyen_cans do 
      collection do 
        post '/update' => 'diem_chuyen_cans#update'
      end
    end    
    resources :lop_mon_hoc_sinh_viens  do 
      collection do 
        post '/groupupdate' => 'lop_mon_hoc_sinh_viens#groupupdate'
        get '/group' => 'lop_mon_hoc_sinh_viens#group'
      end
    end  
    resources :topics do 
      resources :posts
    end  
    resources :can_bo_lops
    resources :tai_lieu_mon_hocs
    resources :thong_bao_lop_hocs
    resources :dang_ky_day_bus
    resources :kien_nghis
    resources :nhat_kies
    resources :ra_som_vao_muons
    resources :day_thays
    resources :nghi_days
    resources :buoihoc do 
      member do
        post 'rate' => 'buoihoc#rate'
        post 'update', :as => 'update'          
        post 'diemdanh'
        get 'diemdanh' => 'buoihoc#get_diemdanh'
        post 'calendar'
        post 'daybu'
        post 'nghiday'
        post 'daythay'
        post 'doigio'
        get 'quanly' => 'buoihoc#get_quanly'
        get 'lichtrinh'
        get 'lichtrinh_edit' => 'buoihoc#lichtrinh_edit'
        post 'lichtrinh' => 'buoihoc#syllabus'        
      end        
    end
  end
  get "quanly" => 'quanly#index', :as => 'quanly'
  match 'quanly/lopghep' => 'quanly#lopghep', :as => 'quanlylopghep'
  match 'quanly/nghiday' => 'quanly#nghiday', :as => 'quanlynghiday'
  match 'quanly/daybu' => 'quanly#daybu', :as => 'quanlydaybu'
  match 'quanly/dkbs' => 'quanly#dkbs', :as => 'quanlydkbs'
  post 'quanly/filtersv' => 'quanly#filtersv', :as => 'filtersv'
  post 'quanly/filterlophc' => 'quanly#filterlophc', :as => 'filterlophc'
  post 'quanly/filterloptc' => 'quanly#filterloptc', :as => 'filterloptc'
  post 'quanly/checklopghep' => 'quanly#checklopghep', :as => 'checklopghep'
  post 'quanly/updatelopghep' => 'quanly#updatelopghep', :as => 'updatelopghep'
  post 'quanly/movelopghep' => 'quanly#movelopghep', :as => 'movelopghep'
  post 'quanly/qlnghiday' => 'quanly#qlnghiday', :as => 'qlnghiday'
  post 'quanly/qldaybu' => 'quanly#qldaybu', :as => 'qldaybu'
  post 'quanly/qldkbs' => 'quanly#qldkbs', :as => 'qldkbs'
  get 'quanly/phongtrong' => 'quanly#phongtrong', :as => 'phongtrong'
  post 'quanly/getphongtrong' => 'quanly#getphongtrong', :as => 'getphongtrong'
  match 'quanly/nghidayhangloat' => 'quanly#nghidayhangloat', :as => 'nghidayhangloat'
  post 'quanly/post_nghidayhangloat' => 'quanly#post_nghidayhangloat', :as => 'post_nghidayhangloat'
  post 'quanly/huynghiday' => 'quanly#huynghiday', :as => 'huynghiday'
  get "quanly/report1" => 'quanly#report1', :as => 'report1'
  get "quanly/report2/(:tuan)" => 'quanly#report2', :as => 'report2'
  get "quanly/report3" => 'quanly#report3', :as => 'report3'
  get "quanly/report4/(:tuan)" => 'quanly#report4', :as => 'report4'
  get "quanly/report5/(:tuan)" => 'quanly#report5', :as => 'report5'
  get "monitor" => 'monitor#index', :as => 'monitor'
  get "monitor/activity" => 'monitor#activity', :as => 'activity'
  get "monitor/:lop_mon_hoc_id/:id" => 'monitor#show', :as => 'showmonitor'
  get "monitor/daybu/:lop_mon_hoc_id/:id" => 'monitor#showdaybu', :as => 'showmonitordaybu'
  get "admin" => 'admin#index', :as => 'admin'
  get "trucnhat" => 'monitor#trucnhat', :as => 'trucnhat'
  get "thanhtra" => 'monitor#thanhtra', :as => 'thanhtra'
  get "quanly/vipham" => 'quanly#vipham', :as => 'vipham'
  post "quanly/qlvipham" => 'quanly#qlvipham', :as => 'qlvipham'
  get "quanly/qlvipham(/:tuan)" => 'quanly#qlvipham', :as => 'qlvipham'
  get "monitor/:lop_mon_hoc_id/:phong/:id/trucnhat" => 'monitor#showtrucnhat', :as => 'showtrucnhat'
  get "monitor/:lop_mon_hoc_id/:phong/:id/thanhtra" => 'monitor#showthanhtra', :as => 'showthanhtra'
  post "monitor/qltrucnhat" => 'monitor#qltrucnhat', :as => 'qltrucnhat'
  post "monitor/qlthanhtra" => 'monitor#qlthanhtra', :as => 'qlthanhtra'  
  get "search" => 'dashboard#search', :as => 'search'
  match '*a', :to => 'application#routing'
  
  

  

end

app/controllers/diem_chuyen_cans_controller.rb
#encoding : UTF-8
class DiemChuyenCansController < ApplicationController
  before_filter :load_lop
  # GET /diem_chuyen_cans
  # GET /diem_chuyen_cans.json
  def index
    #authorize! :read, @lop_mon_hoc
    authorize! :quanly, @lop_mon_hoc if current_user.is_a?(GiangVien)
    authorize! :read, @lop_mon_hoc if current_user.is_a?(SinhVien)
    @svs = @lop_mon_hoc.lop_mon_hoc_sinh_viens.order('ten asc')
    QC.enqueue "GoogleAnalytic.perform", {:category => "Diemchuyencan", :action => "index", :label => "#{current_user.username}", :value => "1"}.to_json
    respond_to do |format|
      format.html do 
        if @lop_mon_hoc.da_day_xong
          render :index2
        else
          if can? :manage, @lop_mon_hoc
            render :index
          elsif can? :read, @lop_mon_hoc
            render :index_sv
          end
        end
      end
    end   
  end
  def update
    authorize! :manage, @lop_mon_hoc
    @svs = @lop_mon_hoc.lop_mon_hoc_sinh_viens
    if @svs and @svs.count > 0
      @svs.each do |sv|
        sv.diem_chuyen_can = sv.diemcc
        sv.diem_qua_trinh = sv.diemqt
        sv.save!
      end
    end
    QC.enqueue "GoogleAnalytic.perform", {:category => "Diemchuyencan", :action => "update", :label => "#{current_user.username}", :value => "1"}.to_json
    respond_to do |format|
      format.js
    end
  end
  # POST /diem_chuyen_cans
  # POST /diem_chuyen_cans.json
  def create
    #todo
    authorize! :manage, @lop_mon_hoc
    @msvs = params[:msv]
    @svs = @lop_mon_hoc.lop_mon_hoc_sinh_viens.order('ten asc')
    @error = ""
    @svs.each do |sv|
      if @msvs[sv.ma_sinh_vien].present? and @msvs[sv.ma_sinh_vien].to_i >= 0 and @msvs[sv.ma_sinh_vien].to_i <= 4
        sv.diem_chuyen_can = @msvs[sv.ma_sinh_vien].to_i
        sv.diem_qua_trinh = sv.diemqt
        if sv.diem_chuyen_can == 0 
          sv.note = "TC"
        else
          sv.note = nil
        end
        sv.create_activity key: "lop_mon_hoc_sinh_vien.updatediemchuyencan", params: {dcc1: sv.diemcc, dcc2: sv.diem_chuyen_can}, owner: current_user, recipient: sv.sinh_vien
        sv.save! rescue puts "error"
      else
        @error +=  sv.ma_sinh_vien + ", "
      end      
    end    
    QC.enqueue "GoogleAnalytic.perform", {:category => "Diemchuyencan", :action => "create", :label => "#{current_user.username}", :value => "1"}.to_json
    respond_to do |format|
      format.js
    end
  end
 

  

  protected
  def load_lop
    @lop_mon_hoc = LopMonHoc.find(params[:lop_mon_hoc_id])      
    @malop = @lop_mon_hoc.ma_lop
    @mamonhoc = @lop_mon_hoc.ma_mon_hoc
    
    
  end
end

app/views/diem_chuyen_cans/_diemcc.html.haml
%table{:class => "table table-bordered table-condensed"}
  %colgroup
    %col{:style => "width: 3%"}
    %col{:style => "width: 10%"}
    %col{:style => "width: 17%"}
    %col{:style => "width: 10%"}
    %col{:style => "width: 10%"}
    %col{:style => "width: 15%"}
    %col{:style => "width: 12%"}
    %col{:style => "width: 8%"}
    %col{:style => "width: 15%"}
  %thead
    %td STT
    %td Mã sinh viên
    %td Họ đệm
    %td Tên   
    %td Lớp                  
    %td Tình hình học tập
    %td Có phép
    %td Tổng số vắng        
    %td Điểm chuyên cần (Thang 4) 
  %tbody
    - @svs.each_with_index do |sv, index|
      %tr
        %td= (index+1).to_s
        %td= sv.ma_sinh_vien            
        %td= sv.hodemdaydu
        %td= sv.ten  
        %td= sv.ma_lop_hanh_chinh
        %td.progress  
          .bar.bar-danger{:style => "width: #{100 - sv.percent}%"}
          .bar.bar-success{:style => "width: #{sv.percent}%"}= sv.percent.to_s + "%"                               
        %td= sv.so_vang_co_phep || 0
        %td= sv.so_tiet_vang ||0            
        %td= text_field_tag "msv[#{sv.ma_sinh_vien}", nil, :value => sv.diem_chuyen_can || sv.diemcc || "", :style => "width: 20px;"

app/views/diem_chuyen_cans/create.js.haml
- if @error and @error.length > 0
  alert("Vui lòng kiểm tra lại những sinh viên sau: #{@error[0..-1]}");
- else
  alert("Đã cập nhật thành công");

app/views/diem_chuyen_cans/index.html.haml
 
.container-fluid
  .navbar.navbar-fixed-top
    .navbar-inner
      .container-fluid
        %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.brand{:href => "/" } HPU
        .container.nav-collapse
          %ul.nav.pull-left#urls            
            %li= link_to "Thông tin chung", lop_mon_hoc_path(@lop_mon_hoc.id)  
            %li.dropdown
              %a.dropdown-toggle{:href => "#", :'data-toggle' => "dropdown"} 
                Điểm
                %b.caret
              %ul.dropdown-menu
                - if @lop_mon_hoc.get_thuc_hanh
                  %li= link_to "Điểm nhóm thực hành", lop_mon_hoc_diem_chi_tiets_path(@lop_mon_hoc.id) + "/2"
                %li.active= link_to "Điểm chuyên cần", lop_mon_hoc_diem_chuyen_cans_path(@lop_mon_hoc.id) 
                %li= link_to "Điểm kiểm tra", lop_mon_hoc_diem_chi_tiets_path(@lop_mon_hoc.id)
            %li.dropdown
              %a.dropdown-toggle{:href => "#", :'data-toggle' => "dropdown"} 
                - if can? :manage, @lop_mon_hoc
                  Quản lý
                - else
                  Tiện ích
                %b.caret
              %ul.dropdown-menu
                %li= link_to "Thông báo", lop_mon_hoc_thong_bao_lop_hocs_path(@lop_mon_hoc.id)  
                %li= link_to "Diễn đàn", lop_mon_hoc_topics_path(@lop_mon_hoc.id)
                - if can? :manage, @lop_mon_hoc
                  %li= link_to "Quản lý lớp học", lop_mon_hoc_lop_mon_hoc_sinh_viens_path(@lop_mon_hoc.id)
                %li= link_to "Thời khóa biểu", lop_mon_hoc_path(@lop_mon_hoc.id)+'/calendar'
          %ul.nav.pull-right              
            %li
              %a{:href => "#myModal", :role => "button", :"data-toggle" => "modal"} Hướng dẫn
            %li= link_to 'Đăng xuất',destroy_user_session_path                          
                
.container-fluid{:style=>"margin-top: 100px;"}
  #myModal.modal.hide.fade{:tabindex => "-1", :role => "dialog", :"aria-labelledby" => "myModalLabel", :"aria-hidden" => "true"}
    .modal-header
      %button.close{:type => "button", :"data-dismiss" => "modal", :"aria-hidden" => "true"} ×
      %h3#myModalLabel Hướng dẫn sử dụng
    .modal-body        
      %p - Bạn có thể trực tiếp thay đổi điểm chuyên cần ở đây.
      %p - Khi cần bạn có thể tính toán lại điểm chuyên cần bằng cách nhấn vào nút tính toán lại điểm chuyên cần
    .modal-footer
      %button.btn{:"data-dismiss" => "modal", :"aria-hidden" => "true"} Close
      %button.btn.btn-primary Save changes

  = form_tag lop_mon_hoc_diem_chuyen_cans_path(@lop_mon_hoc.id) + "/update", :method => :post, :remote => true do
    = submit_tag "Tính toán lại điểm chuyên cần", :class => "btn btn-primary",  :data => {disable_with: "Submitting..."}    
  = form_tag lop_mon_hoc_diem_chuyen_cans_path(@lop_mon_hoc.id), :method => :post, :remote => true do
    - if can? :manage, @lop_mon_hoc
      = submit_tag "Cập nhật", :class => "btn btn-primary",  :data => {disable_with: "Submitting..."}
    #diemcc
      = render "diemcc"

app/views/diem_chuyen_cans/index2.html.haml
.container-fluid
  .navbar.navbar-fixed-top
    .navbar-inner
      .container-fluid
        %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.brand{:href => "/" } HPU
        .container.nav-collapse
          %ul.nav.pull-left#urls            
            %li= link_to "Thông tin chung", lop_mon_hoc_path(@lop_mon_hoc.id)  
            %li.dropdown
              %a.dropdown-toggle{:href => "#", :'data-toggle' => "dropdown"} 
                Điểm
                %b.caret
              %ul.dropdown-menu
                - if @lop_mon_hoc.get_thuc_hanh
                  %li= link_to "Điểm nhóm thực hành", lop_mon_hoc_diem_chi_tiets_path(@lop_mon_hoc.id) + "/2"
                %li.active= link_to "Điểm chuyên cần", lop_mon_hoc_diem_chuyen_cans_path(@lop_mon_hoc.id) 
                %li= link_to "Điểm kiểm tra", lop_mon_hoc_diem_chi_tiets_path(@lop_mon_hoc.id)
            %li.dropdown
              %a.dropdown-toggle{:href => "#", :'data-toggle' => "dropdown"} 
                Tiện ích
                %b.caret
              %ul.dropdown-menu
                %li= link_to "Thông báo", lop_mon_hoc_thong_bao_lop_hocs_path(@lop_mon_hoc.id)  
                %li= link_to "Diễn đàn", lop_mon_hoc_topics_path(@lop_mon_hoc.id)
                %li= link_to "Thời khóa biểu", lop_mon_hoc_path(@lop_mon_hoc.id)+'/calendar'
          %ul.nav.pull-right            
            %li= link_to 'Đăng xuất',destroy_user_session_path                          
            
.container-fluid{:style=>"margin-top: 100px;"}  
    
  %table{:class => "table datatable"}
    %colgroup
      %col{:style => "width: 10%"}
      %col{:style => "width: 10%"}
      %col{:style => "width: 20%"}
      %col{:style => "width: 10%"}
      %col{:style => "width: 10%"}
      %col{:style => "width: 15%"}
      %col{:style => "width: 12%"}
      %col{:style => "width: 8%"}
      %col{:style => "width: 15%"}
    %thead
      %td STT
      %td Mã sinh viên
      %td Họ đệm
      %td Tên   
      %td Lớp                  
      %td Tình hình vắng
      %td Có phép
      %td Tổng số vắng        
      %td Điểm chuyên cần 
    %tbody
      - @svs.each_with_index do |sv, index|
        %tr
          %td= (index+1).to_s
          %td= sv.ma_sinh_vien
          %td= sv.hodemdaydu
          %td= sv.ten  
          %td= sv.ma_lop_hanh_chinh
          %td.progress  
            .bar.bar-danger{:style => "width: #{((sv.so_tiet_vang if sv) || 0)*100/(@lop_mon_hoc.so_tiet || 1)}%"}                                        
            .bar.bar-success{:style => "width: #{100-((sv.so_tiet_vang if sv) || 0)*100/(@lop_mon_hoc.so_tiet || 1)}%"}= (100-(sv.so_tiet_vang || 0)).to_s + "%"
          %td= sv.so_vang_co_phep || 0
          %td= sv.so_tiet_vang ||0            
          %td= sv.diem_chuyen_can || sv.diemcc || ""

app/views/diem_chuyen_cans/index_sv.html.haml
.container-fluid
  .navbar.navbar-fixed-top
    .navbar-inner
      .container-fluid
        %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.brand{:href => "/" } HPU
        .container.nav-collapse
          %ul.nav.pull-left#urls            
            %li= link_to "Thông tin chung", lop_mon_hoc_path(@lop_mon_hoc.id)  
            %li.dropdown
              %a.dropdown-toggle{:href => "#", :'data-toggle' => "dropdown"} 
                Điểm
                %b.caret
              %ul.dropdown-menu
                - if @lop_mon_hoc.get_thuc_hanh
                  %li= link_to "Điểm nhóm thực hành", lop_mon_hoc_diem_chi_tiets_path(@lop_mon_hoc.id) + "/2"
                %li.active= link_to "Điểm chuyên cần", lop_mon_hoc_diem_chuyen_cans_path(@lop_mon_hoc.id) 
                %li= link_to "Điểm kiểm tra", lop_mon_hoc_diem_chi_tiets_path(@lop_mon_hoc.id)
            %li.dropdown
              %a.dropdown-toggle{:href => "#", :'data-toggle' => "dropdown"} 
                Tiện ích
                %b.caret
              %ul.dropdown-menu
                %li= link_to "Thông báo", lop_mon_hoc_thong_bao_lop_hocs_path(@lop_mon_hoc.id)  
                %li= link_to "Diễn đàn", lop_mon_hoc_topics_path(@lop_mon_hoc.id)
                %li= link_to "Thời khóa biểu", lop_mon_hoc_path(@lop_mon_hoc.id)+'/calendar'
          %ul.nav.pull-right            
            %li= link_to 'Đăng xuất',destroy_user_session_path                          
            
.container-fluid{:style=>"margin-top: 100px;"}  
    
  %table{:class => "table datatable"}
    %colgroup
      %col{:style => "width: 10%"}
      %col{:style => "width: 20%"}
      %col{:style => "width: 10%"}
      %col{:style => "width: 10%"}
      %col{:style => "width: 15%"}
      %col{:style => "width: 12%"}
      %col{:style => "width: 8%"}
      %col{:style => "width: 15%"}
    %thead
      %td Mã sinh viên
      %td Họ đệm
      %td Tên   
      %td Lớp                  
      %td Tình hình học tập
      %td Có phép
      %td Tổng số vắng        
      %td Điểm chuyên cần 
    %tbody
      - @svs.each_with_index do |sv, index|
        %tr
          %td= (index+1).to_s
          %td= sv.ma_sinh_vien
          %td= sv.hodemdaydu
          %td= sv.ten  
          %td= sv.ma_lop_hanh_chinh
          %td.progress  
            .bar.bar-danger{:style => "width: #{((sv.so_tiet_vang if sv) || 0)*100/(@lop_mon_hoc.so_tiet || 1)}%"}                                        
            .bar.bar-success{:style => "width: #{100-((sv.so_tiet_vang if sv) || 0)*100/(@lop_mon_hoc.so_tiet || 1)}%"}= (100-(sv.so_tiet_vang || 0)).to_s + "%"
          %td= sv.so_vang_co_phep || 0
          %td= sv.so_tiet_vang ||0            
          %td= sv.diem_chuyen_can || sv.diemcc || ""

app/views/diem_chuyen_cans/update.js.haml
s = $("#diemcc");    
s.empty();
s.html("#{escape_javascript(render :partial => 'diemcc')}");
alert("Cập nhật thành công");