config/routes.rb
Trytest::Application.routes.draw do
  
  
  
  ActiveAdmin.routes(self)

  namespace :api, :defaults => {:format => :json} do
    namespace :v1 do
      resources :tkb_giang_viens
      resources :lop_mon_hoc_sinh_viens
      resources :sinh_viens do 
        member do 
          get 'trucnhat' => 'sinh_viens#trucnhat'
          get 'tkb' => 'sinh_viens#tkb'
        end
      end
      resources :giang_viens
      resources :lop_mon_hocs
    end
  end

  match '/rate' => 'rater#create', :as => 'rate'

  get "dashboard/index"
  match '/activity' => "dashboard#activity", :as => "activity"
  match '/calendar' => 'dashboard#calendar', :as => "calendar"
  match '/post_calendar' => 'dashboard#post_calendar', :as => "post_calendar"
  match 'tuan/:id' => 'dashboard#show', :as => "tuan"
  get "dashboard/access_denied", :as => "access_denied"
   root :to => 'dashboard#index'
  devise_for :users do
   get '/users/sign_out' => 'devise/cas_sessions#destroy'
  end
  
  
  
  resources :users
  resources :giang_viens do 
    member do 
      get '/report' => 'giang_viens#report'
    end
  end
  resources :mon_hocs
  resources :sinh_viens
  resources :phongs
  resources :lop_mon_hocs do           
    resources :tkb_giang_viens      
    member do 
      post '/update_hoten' => 'lop_mon_hocs#update_hoten'
      post '/update_diemqt' => 'lop_mon_hocs#update_diemqt'
      post '/update_diemcc' => 'lop_mon_hocs#update_diemcc'
      get '/nhap_diem_thang_3' => 'lop_mon_hocs#nhapdiemthang3', :as => 'nhapdiemthang3'
      post '/postnhapdiemthang3' => 'lop_mon_hocs#postnhapdiemthang3', :as => 'postnhapdiemthang3'
      get '/calendar' => 'lop_mon_hocs#calendar'        
      get '/search' => 'lop_mon_hocs#search'
      get '/report' => 'lop_mon_hocs#report'
      get '/t/:tuan_id' => 'lop_mon_hocs#tuan'
      get '/showdkbs' => 'lop_mon_hocs#showdkbs', :as => 'showdkbs'
      post '/dkbs' => 'lop_mon_hocs#dkbs', :as => 'dkbs'
      post '/qldkbs' => 'lop_mon_hocs#qldkbs', :as => 'qldkbs'
      get '/lichtrinh' => 'lop_mon_hocs#lichtrinh', :as => 'lichtrinh'
      get '/tinhhinh' => 'lop_mon_hocs#tinhhinh', :as => 'tinhhinh'
      get 'phieudiem'
    end    
    resources :diem_chi_tiets      do  
      collection do        
        get '/:loai' => 'diem_chi_tiets#index'
        post '/:loai'  => 'diem_chi_tiets#create'
      end
    end
    resources :diem_chuyen_cans do 
      collection do 
        post '/update' => 'diem_chuyen_cans#update'
      end
    end    
    resources :lop_mon_hoc_sinh_viens  do 
      collection do 
        post '/groupupdate' => 'lop_mon_hoc_sinh_viens#groupupdate'
        get '/group' => 'lop_mon_hoc_sinh_viens#group'
      end
    end  
    resources :topics do 
      resources :posts
    end  
    resources :can_bo_lops
    resources :tai_lieu_mon_hocs
    resources :thong_bao_lop_hocs
    resources :dang_ky_day_bus
    resources :kien_nghis
    resources :nhat_kies
    resources :ra_som_vao_muons
    resources :day_thays
    resources :nghi_days
    resources :buoihoc do 
      member do
        post 'rate' => 'buoihoc#rate'
        post 'update', :as => 'update'          
        post 'diemdanh'
        get 'diemdanh' => 'buoihoc#get_diemdanh'
        post 'calendar'
        post 'daybu'
        post 'nghiday'
        post 'daythay'
        post 'doigio'
        get 'quanly' => 'buoihoc#get_quanly'
        get 'lichtrinh'
        get 'lichtrinh_edit' => 'buoihoc#lichtrinh_edit'
        post 'lichtrinh' => 'buoihoc#syllabus'        
      end        
    end
  end
  get "quanly" => 'quanly#index', :as => 'quanly'
  match 'quanly/lopghep' => 'quanly#lopghep', :as => 'quanlylopghep'
  match 'quanly/nghiday' => 'quanly#nghiday', :as => 'quanlynghiday'
  match 'quanly/daybu' => 'quanly#daybu', :as => 'quanlydaybu'
  match 'quanly/dkbs' => 'quanly#dkbs', :as => 'quanlydkbs'
  post 'quanly/filtersv' => 'quanly#filtersv', :as => 'filtersv'
  post 'quanly/filterlophc' => 'quanly#filterlophc', :as => 'filterlophc'
  post 'quanly/filterloptc' => 'quanly#filterloptc', :as => 'filterloptc'
  post 'quanly/checklopghep' => 'quanly#checklopghep', :as => 'checklopghep'
  post 'quanly/updatelopghep' => 'quanly#updatelopghep', :as => 'updatelopghep'
  post 'quanly/movelopghep' => 'quanly#movelopghep', :as => 'movelopghep'
  post 'quanly/qlnghiday' => 'quanly#qlnghiday', :as => 'qlnghiday'
  post 'quanly/qldaybu' => 'quanly#qldaybu', :as => 'qldaybu'
  post 'quanly/qldkbs' => 'quanly#qldkbs', :as => 'qldkbs'
  get 'quanly/phongtrong' => 'quanly#phongtrong', :as => 'phongtrong'
  post 'quanly/getphongtrong' => 'quanly#getphongtrong', :as => 'getphongtrong'
  match 'quanly/nghidayhangloat' => 'quanly#nghidayhangloat', :as => 'nghidayhangloat'
  post 'quanly/post_nghidayhangloat' => 'quanly#post_nghidayhangloat', :as => 'post_nghidayhangloat'
  post 'quanly/huynghiday' => 'quanly#huynghiday', :as => 'huynghiday'
  get "quanly/report1" => 'quanly#report1', :as => 'report1'
  get "quanly/report2/(:tuan)" => 'quanly#report2', :as => 'report2'
  get "quanly/report3" => 'quanly#report3', :as => 'report3'
  get "quanly/report4/(:tuan)" => 'quanly#report4', :as => 'report4'
  get "quanly/report5/(:tuan)" => 'quanly#report5', :as => 'report5'
  get "monitor" => 'monitor#index', :as => 'monitor'
  get "monitor/activity" => 'monitor#activity', :as => 'activity'
  get "monitor/:lop_mon_hoc_id/:id" => 'monitor#show', :as => 'showmonitor'
  get "monitor/daybu/:lop_mon_hoc_id/:id" => 'monitor#showdaybu', :as => 'showmonitordaybu'
  get "admin" => 'admin#index', :as => 'admin'
  get "trucnhat" => 'monitor#trucnhat', :as => 'trucnhat'
  get "thanhtra" => 'monitor#thanhtra', :as => 'thanhtra'
  get "quanly/vipham" => 'quanly#vipham', :as => 'vipham'
  post "quanly/qlvipham" => 'quanly#qlvipham', :as => 'qlvipham'
  get "quanly/qlvipham(/:tuan)" => 'quanly#qlvipham', :as => 'qlvipham'
  get "monitor/:lop_mon_hoc_id/:phong/:id/trucnhat" => 'monitor#showtrucnhat', :as => 'showtrucnhat'
  get "monitor/:lop_mon_hoc_id/:phong/:id/thanhtra" => 'monitor#showthanhtra', :as => 'showthanhtra'
  post "monitor/qltrucnhat" => 'monitor#qltrucnhat', :as => 'qltrucnhat'
  post "monitor/qlthanhtra" => 'monitor#qlthanhtra', :as => 'qlthanhtra'  
  get "search" => 'dashboard#search', :as => 'search'
  match '*a', :to => 'application#routing'
  
  

  

end

app/controllers/monitor_controller.rb
require 'pg_tools'
class MonitorController < ActionController::Base
  include MonitorHelper
  include BuoihocHelper  
  before_filter :load_tenant
  before_filter :authenticate_user!  , :except => [:index, :show]
  before_filter :load_tuan
  before_filter :load_phongs

  def index
    @today = @days.select {|d| to_zdate(d["time"][0]) == Date.today }.sort_by {|k| to_zdatetime(k['time'][0])}    
    respond_to do |format|
      format.html {render :index, :layout => 'application'}
    end
  end
  def activity
    @activities = PublicActivity::Activity.order('updated_at desc').take(50)    
    QC.enqueue "GoogleAnalytic.perform", {:category => "Monitor", :action => "activity", :label => "#{current_user.username}", :value => "1"}.to_json
    respond_to do |format|
      format.html {render :activity, :layout => 'application'}
    end
  end
  def show
    @lop_mon_hoc = LopMonHoc.find(params[:lop_mon_hoc_id])
    @ngay = str_to_ngay(params[:id])
    @lich = @lop_mon_hoc.lich_trinh_giang_days.where(ngay_day: get_ngay(@ngay)).first    
    @trucnhat = JSON.parse(@lop_mon_hoc.trucnhat) if @lop_mon_hoc.trucnhat
    @nhomtruc = @trucnhat[from_zdate(params[:id])] if @trucnhat
    @svs = SinhVien.where(ma_sinh_vien: @nhomtruc) if @nhomtruc

    respond_to do |format|
      format.js
    end
  end
  def showdaybu
    @lop_mon_hoc = LopMonHoc.find(params[:lop_mon_hoc_id])
    @ngay = str_to_ngay(params[:id])
    @lich = @lop_mon_hoc.lich_trinh_giang_days.where(ngay_day_moi: get_ngay(@ngay)).first    
    @trucnhat = JSON.parse(@lop_mon_hoc.trucnhat) if @lop_mon_hoc.trucnhat
    @nhomtruc = @trucnhat[from_zdate(params[:id])] if @trucnhat
    @svs = SinhVien.where(ma_sinh_vien: @nhomtruc) if @nhomtruc    
    QC.enqueue "GoogleAnalytic.perform", {:category => "Monitor", :action => "showdaybu", :label => "#{current_user.username}", :value => "1"}.to_json
    respond_to do |format|
      format.js
    end
  end
  def thanhtra
    authorize! :quanly, GiangVien
    dt = Date.today.to_datetime.change(:offset => Rational(7,24))
    @today = @days.select {|d| to_zdate(d["time"][0]) == Date.today }.select {|k| k['phong']}.sort_by {|k| k['phong']}
    @today += @days.select {|d| to_zdate(d["time"][0]) == Date.today }.select {|k| k['phong'].nil?}
    @lichs2 = LichTrucNhat.where("ngay_truc > timestamp ? and ngay_truc < timestamp ?", dt, DateTime.now).order('ngay_truc asc, created_at asc').map {|l| "#{l.lop_mon_hoc.ma_lop}_#{l.lop_mon_hoc.ma_mon_hoc}"}    
    QC.enqueue "GoogleAnalytic.perform", {:category => "Monitor", :action => "thanhtra", :label => "#{current_user.username}", :value => "1"}.to_json
    respond_to do |format|
      format.html {render :thanhtra, :layout => 'application'}
    end
  end
  def qlthanhtra
    authorize! :quanly, GiangVien
    @lenmuon = params[:lenmuon]
    @vesom = (params[:vesom] ? true: false)
    @bogio = (params[:bogio] ? true: false)
    @phong = params[:phong]
    @lop_mon_hoc = LopMonHoc.find(params[:lop_mon_hoc_id])
    @ngay = str_to_ngay(params[:ngay_vi_pham])
    @lich_vi_pham = @lop_mon_hoc.lich_vi_phams.where(ngay_vi_pham: get_ngay(@ngay)).first_or_create!
    @lich_vi_pham.update_attributes(tuan: @current_week, user_id: current_user.id, phong: @phong, lenmuon: @lenmuon, vesom: @vesom, bogio: @bogio, note1: params[:note1])    
    QC.enqueue "GoogleAnalytic.perform", {:category => "Monitor", :action => "qlthanhtra", :label => "#{current_user.username}", :value => "1"}.to_json
    respond_to do |format|
      format.js
    end
  end
  def showthanhtra
    authorize! :quanly, GiangVien
    @lop_mon_hoc = LopMonHoc.find(params[:lop_mon_hoc_id])
    @siso = @lop_mon_hoc.lop_mon_hoc_sinh_viens.count
    @ngay_vi_pham = params[:id]
    @phong = params[:phong]
    @ngay = str_to_ngay(@ngay_vi_pham)
    @lich = @lop_mon_hoc.lich_trinh_giang_days.where(ngay_day: get_ngay(@ngay)).first    
    @lich_vi_pham = @lop_mon_hoc.lich_vi_phams.where(ngay_vi_pham: get_ngay(@ngay)).first        
    QC.enqueue "GoogleAnalytic.perform", {:category => "Monitor", :action => "showthanhtra", :label => "#{current_user.username}", :value => "1"}.to_json
    respond_to do |format|
      format.js
    end
  end
  def trucnhat
    authorize! :quanly, SinhVien
    dt = Date.today.to_datetime.change(:offset => Rational(7,24))
    @today = @days.select {|d| to_zdate(d["time"][0]) == Date.today }.select {|k| k['phong']}.sort_by {|k| k['phong']}
    @today += @days.select {|d| to_zdate(d["time"][0]) == Date.today }.select {|k| k['phong'].nil?}
    @lichs2 = LichTrucNhat.where("ngay_truc > timestamp ? and ngay_truc < timestamp ?", dt, DateTime.now).order('ngay_truc asc, created_at asc').map {|l| "#{l.lop_mon_hoc.ma_lop}_#{l.lop_mon_hoc.ma_mon_hoc}"}    
    QC.enqueue "GoogleAnalytic.perform", {:category => "Monitor", :action => "trucnhat", :label => "#{current_user.username}", :value => "1"}.to_json
    respond_to do |format|
      format.html {render :trucnhat, :layout => 'application'}
    end
  end  
  def qltrucnhat
    authorize! :quanly, SinhVien
    @svs = params[:msv]
    note = params[:note]
    phong = params[:phong]
    @lop_mon_hoc = LopMonHoc.find(params[:lop_mon_hoc_id])
    @ngay = str_to_ngay(params[:ngay_truc])
    @lich = @lop_mon_hoc.lich_truc_nhats.where(ngay_truc: get_ngay(@ngay)).first_or_create!
    @lich.update_attributes(note: note, phong: phong, tuan: @current_week, user_id: current_user.id)
    if @lich.truc_nhats.count > 0
      @lich.truc_nhats.update_all(status: false)
    end
    if @svs and @svs.keys.count > 0
      @svs.keys.each do |sv|
        sv1 = @lich.truc_nhats.where(ma_sinh_vien: sv).first_or_create!
        sv1.update_attributes(status: true)
      end
    end    
    QC.enqueue "GoogleAnalytic.perform", {:category => "Monitor", :action => "qltrucnhat", :label => "#{current_user.username}", :value => "1"}.to_json
    respond_to do |format|
      format.js
    end
  end
  def showtrucnhat
    authorize! :quanly, SinhVien
    @lop_mon_hoc = LopMonHoc.find(params[:lop_mon_hoc_id])
    @siso = @lop_mon_hoc.lop_mon_hoc_sinh_viens.count
    @ngay_truc = params[:id]
    @ngay = str_to_ngay(params[:id])
    @lich = @lop_mon_hoc.lich_trinh_giang_days.where(ngay_day: get_ngay(@ngay)).first    
    @lichtrucnhat = @lop_mon_hoc.lich_truc_nhats.where(ngay_truc: get_ngay(@ngay)).first
    @trucnhat = JSON.parse(@lop_mon_hoc.trucnhat) if @lop_mon_hoc.trucnhat
    @nhomtruc = @trucnhat[from_zdate(params[:id])] if @trucnhat
    @svs = SinhVien.where(ma_sinh_vien: @nhomtruc) if @nhomtruc
    if @lichtrucnhat
      @kotruc = @lichtrucnhat.truc_nhats.where(status: true).map {|t| t and t.ma_sinh_vien}
      @note = @lichtrucnhat.note
    end
    @phong = params[:phong]
    if @lich 
      @svvangs = @lich.diem_danhs.vang
    end    
    QC.enqueue "GoogleAnalytic.perform", {:category => "Monitor", :action => "showtrucnhat", :label => "#{current_user.username}", :value => "1"}.to_json
    respond_to do |format|
      format.js
    end
  end
  protected

  def load_tenant

    if @current_tenant ||= Tenant.last     
      PgTools.set_search_path @current_tenant.scheme    
     
    else
      PgTools.restore_default_search_path
     
    end
  end
  def load_tuan
    @week = current_tuan
    @current_week = @week.stt    
    @days = JSON.parse(@week.days)["ngay"]
  end
  def load_phongs
    
    dt = Date.today.to_datetime.change(:offset => Rational(7,24))
    tomorrow = dt + 1.day
    #@tiet = LichTrinhGiangDay.xac_dinh_gio(dt).change(:offset => Rational(7,24))
    @lichs = LichTrinhGiangDay.where("ngay_day > timestamp ? and ngay_day < timestamp ? and loai is null", dt, DateTime.now).order('ngay_day asc, created_at asc')
    @lichs2 = LichTrinhGiangDay.where("ngay_day > timestamp ? and ngay_day < timestamp ? and loai is null", dt, DateTime.now).order('ngay_day asc, created_at asc').map {|l| "#{l.lop_mon_hoc.ma_lop}_#{l.lop_mon_hoc.ma_mon_hoc}"}
    #@currents = LichTrinhGiangDay.current.map {|l| l and "#{l.lop_mon_hoc.ma_lop}_#{l.lop_mon_hoc.ma_mon_hoc}"}
    @lichdaybus = LichTrinhGiangDay.where("ngay_day_moi > timestamp ? and loai = 2 and status = 3 and ngay_day_moi < timestamp ?", dt, tomorrow).order('ngay_day_moi asc, created_at asc')
    #@res2 = @res.select {|n| to_zdate(n["time"][0]) == Date.today}
    #.map {|tkb| tkb and JSON.parse(tkb.days)["ngay"] }
    #.select {|n| to_zdate(n["time"][0]) == Date.today}

  end	
  
end

app/helpers/monitor_helper.rb
#encoding: UTF-8
module MonitorHelper	
	def to_zdate(str)
    DateTime.strptime(str.gsub("T","-").gsub("Z",""), "%Y-%m-%d-%H:%M").change(:offset => Rational(7,24)).to_date
  end
  def to_zdatetime(str)
    DateTime.strptime(str.gsub("T","-").gsub("Z",""), "%Y-%m-%d-%H:%M").change(:offset => Rational(7,24))
  end
  def current_tuan
    Tuan.all.detect {|t| t.tu_ngay.localtime <= DateTime.now and t.den_ngay.localtime >= DateTime.now }
  end
  def from_zdate(str)
    str1 = str.split("-").to_a
     str2 = str1[0]+"-"+str1[1]+"-"+str1[2]+"T"+str1[3]+":"+str1[4]+":00Z"
     return str2
  end
  def check_trucnhat(nhom, sv)
    return false unless nhom
    nhom.include?(sv)
  end
  def getdiemdanh(lich)
    return "Chưa điểm danh" unless lich
    (lich.siso - lich.diem_danhs.vang.count) if lich
  end
end

app/views/monitor/_trucnhat.html.haml
%h5{:style => "text-align:center;"}= "Phòng: #{@phong}, lớp: #{@lop_mon_hoc.ma_lop}, giảng viên: #{@lop_mon_hoc.ten_giang_vien}, sĩ số: #{getdiemdanh(@lich)}/ #{@siso}"
= form_tag qltrucnhat_path, :method => :post, :remote => true do                         
  = hidden_field_tag :lop_mon_hoc_id
  = hidden_field_tag :ngay_truc
  = hidden_field_tag :phong
  .row-fluid    
    .span8
      %h5 Danh sách sinh viên trực nhật:
      %table{:class => "table table-bordered"}           
        %thead          
          %td Mã sinh viên   
          %td Họ và tên
          %td Lớp hành chính
          %td Không trực nhật
        %tbody
          - if @svs      
            - @svs.each_with_index do |sv, index|
              %tr                
                %td= link_to sv.ma_sinh_vien, sinh_vien_path(sv.ma_sinh_vien)
                %td= sv.ho + " " + sv.fullname                
                %td= sv.lop_hc
                %td= check_box_tag "msv[#{sv.ma_sinh_vien}]",nil, check_trucnhat(@kotruc, sv.ma_sinh_vien)
    .span4
      %br
      %br
      %table{:class => "table table-bordered"}        
        %thead                  
          %td Lí do
        %tbody
          %tr
            %td= text_area_tag "note", raw(@note)
    %br    
  - if @svvangs and @svvangs.count > 0
    .row-fluid
      .span8
        %h5 Danh sách sinh viên vắng:
        %table{:class => "table table-bordered"}
          %thead
            %td Mã sinh viên   
            %td Họ và tên
            %td Lớp hành chính
          %tbody
            - @svvangs.each do |dd|
              %tr                
                %td= link_to dd.sinh_vien.ma_sinh_vien, sinh_vien_path(dd.sinh_vien.ma_sinh_vien)
                %td= dd.sinh_vien.ho + " " + dd.sinh_vien.fullname                
                %td= dd.sinh_vien.lop_hc
          

  = submit_tag "Cập nhật trực nhật", :class => "btn btn-primary",  :data => {disable_with: "Submitting..."}

app/views/monitor/index.html.haml
.container-fluid
  .navbar.navbar-fixed-top
    .navbar-inner
      .container-fluid
        %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.brand{:href => "/" } HPU
        .container.nav-collapse          
          %ul.nav.pull-right   
            - if user_signed_in?               
              %li= link_to "Đăng xuất", destroy_user_session_path
            - else
              %li= link_to "Đăng nhập", new_user_session_path
.container-fluid{:style=>"margin-top: 4%;"} 
  #mymodal.modal.hide.fade{:tabindex => -1, :role => "dialog", :'area-hidden' => true}
    .modal-header
      %button{:type => "button", :class => "close", :"data-dismiss" => "modal", :"aria-hidden" => true} x
      %h3 Thông tin giờ học
    .modal-body#modalbody
  .row-fluid
    %ul.nav.pull-right
      - if user_signed_in?  
        %li
          %i
            %strong
              %span= current_user.fullname
      %li
        %i
          %span= "Bây giờ là " + DateTime.now.strftime("%Hh:%M") + " ngày " + DateTime.now.strftime("%d/%m")
      %li
        %i
          %span= "Tuần #{@current_week}: Từ ngày #{@week.tu_ngay.localtime.mday}/#{@week.tu_ngay.localtime.mon}, đến ngày #{@week.den_ngay.localtime.mday}/#{@week.den_ngay.localtime.mon}"  
  .row-fluid    
  %table#monitor{:class => "table table-bordered table-condensed"}    
    %thead
      %td STT
      %td Mã lớp
      %td Tên môn
      %td Ca
      %td Giờ dạy      
      %td Số tiết dạy
      %td Phòng     
      %td Giảng viên
    %tbody
      - if @today and @today.count > 0
        - @today.each_with_index do |lich, index|                    
          %tr{:class => ( @lichs2.include?("#{lich['ma_lop']}_#{lich['ma_mon_hoc']}") ? "success" : "error" ) }            
            %td= so(index+1)            
            %td= link_to lich['ma_lop'] + ( @lichs2.include?("#{lich['ma_lop']}_#{lich['ma_mon_hoc']}") ? " * " : " " ), showmonitor_path(lich['lop'], to_zdatetime(lich['time'][0]).strftime("%Y-%m-%d-%H-%M")), :remote => true            
            %td= lich['ten_mon_hoc']
            %td= "Ca" + (LichTrinhGiangDay.ca(to_zdatetime(lich['time'][0])).to_s || "")
            %td= to_zdatetime(lich['time'][0]).strftime("%Hh:%M")
            %td= lich['so_tiet']
            %td= (lich['phong'] || "") 
            %td= lich['ten_giang_vien']
  .row-fluid
    %h3 Lịch dạy bù:
    %table#monitor{:class => "table table-bordered table-condensed"}    
      %thead
        %td STT
        %td Mã lớp
        %td Tên môn
        %td Ca
        %td Giờ dạy      
        %td Số tiết dạy
        %td Phòng     
        %td Giảng viên
      %tbody
        - if @lichdaybus and @lichdaybus.count > 0
          - @lichdaybus.each_with_index do |lich, index|
            %tr{:class => (index % 2 == 0 ? "warning" : "info")}        
              %td= so(index+1)            
              %td= link_to lich.lop_mon_hoc.ma_lop, showmonitordaybu_path(lich.lop_mon_hoc.id, lich.ngay_day_moi.localtime.strftime("%Y-%m-%d-%H-%M")), :remote => true
              %td= lich.lop_mon_hoc.ten_mon_hoc
              %td= "Ca" + (LichTrinhGiangDay.ca(lich.ngay_day_moi.localtime.to_datetime).to_s || "")
              %td= lich.ngay_day_moi.localtime.strftime("%Hh:%M")
              %td= lich.so_tiet_day_moi
              %td= (lich.phong_moi || "") 
              %td= lich.lop_mon_hoc.ten_giang_vien

app/views/monitor/qlthanhtra.js.haml
alert("Cập nhật thành công");

app/views/monitor/qltrucnhat.js.haml
alert("OK");

app/views/monitor/thanhtra.html.haml
.container-fluid
  .navbar.navbar-fixed-top
    .navbar-inner
      .container-fluid
        %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.brand{:href => "/" } HPU
        .container.nav-collapse          
          %ul.nav.pull-right   
            - if user_signed_in?               
              %li= link_to "Đăng xuất", destroy_user_session_path
            - else
              %li= link_to "Đăng nhập", new_user_session_path
.container-fluid{:style=>"margin-top: 4%;"}   
  .row-fluid
    %ul.nav.pull-right
      - if user_signed_in?  
        %li
          %i
            %strong
              %span= current_user.fullname
      %li
        %i
          %span= "Bây giờ là " + DateTime.now.strftime("%Hh:%M") + " ngày " + DateTime.now.strftime("%d/%m")
      %li
        %i
          %span= "Tuần #{@current_week}: Từ ngày #{@week.tu_ngay.localtime.mday}/#{@week.tu_ngay.localtime.mon}, đến ngày #{@week.den_ngay.localtime.mday}/#{@week.den_ngay.localtime.mon}"  
  .row-fluid  
    #tn  
  .row-fluid
    %table#monitor{:class => "table table-bordered table-condensed"}    
      %thead
        %td STT
        %td Phòng  
        %td Mã lớp
        %td Tên môn        
        %td Giờ dạy      
        %td Số tiết dạy           
        %td Giảng viên
      %tbody
        - if @today and @today.count > 0
          - @today.each_with_index do |lich, index|                    
            %tr{:class => ( @lichs2.include?("#{lich['ma_lop']}_#{lich['ma_mon_hoc']}") ? "success" : "error" ) }            
              %td= so(index+1)    
              %td= link_to (lich['phong'] || ""), phong_path(lich['phong'] || "")
              %td= link_to lich['ma_lop'] + ( @lichs2.include?("#{lich['ma_lop']}_#{lich['ma_mon_hoc']}") ? " * " : " " ), "/monitor/#{lich['lop']}/#{lich['phong']}/#{to_zdatetime(lich['time'][0]).strftime("%Y-%m-%d-%H-%M")}/thanhtra", :remote => true            
              %td= lich['ten_mon_hoc']              
              %td= to_zdatetime(lich['time'][0]).strftime("%Hh:%M")
              %td= lich['so_tiet']              
              %td= link_to lich['ten_giang_vien'], giang_vien_path(lich['ma_giang_vien'])
  